baseURL = "https://carly.netlify.app"
languageCode = "en-us"
[[menu.main]]
name = "Testimonials"
parent = "Resources"
url = "/testimonials"
weight = 3
[[menu.main]]
name = "Our Team"
parent = "Resources"
url = "/teams"
weight = 2
[[menu.main]]
name = "Our Partners"
parent = "Resources"
url = "/partners"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Resources"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[taxonomies]
category = "categories"
project = "projects"
tag = "tags"
