baseURL = "https://coffeeintocoding.com/"
languageCode = "en-us"
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
category = "categories"
project = "projects"
tag = "tags"
